version: '3.8'

services:
  ticket-master:
    image: mikumifa/bili-ticket-storm-master:latest
    networks:
      - bili-ticket-storm-network
    environment:
      - CONFIG_PATH=/app/data
    volumes:
      - ${PWD}/data:/app/data

  ticket-worker:
    image: mikumifa/bili-ticket-storm-worker:latest
    networks:
      - bili-ticket-storm-network
    environment:
      - MASTER_SERVER_ADDR=ticket-master:40052
      - PUSHPLUS_TOKEN=
      - TICKET_INTERVAL=
      - GT_BASE_URL=http://gt-python:8000
#      - TICKET_TIME_START=2006-01-02T15:04
    depends_on:
      - ticket-master
      - gt-python
    deploy:
      mode: global # global模式会让每台机器运行一个实例
      # 或 replicas: 5 来自己设定worker数量

  gt-python:
    image: mikumifa/bili-ticket-storm-gt-python:latest
    container_name: gt-python-service
    restart: unless-stopped
    networks:
      - bili-ticket-storm-network

networks:
  bili-ticket-storm-network:
    driver: overlay
    attachable: true
    name: bili-ticket-storm-network
